config/routes.rb
Mymaison::Application.routes.draw do
  root 'reservations#index'

  resources :reservations do
    resources :guests
  end
  post 'reservations/submit/:reservation_id' => 'reservations#submit', as: 'reservation_submit'
  get 'reservations/signed/:reservation_id' => 'reservations#signed', as: 'reservation_signed'
  post 'reservations/email_contract/:reservation_id' => 'reservations#email_contract', as: 'reservation_email_contract'
  post 'reservations/download_contract/:reservation_id' => 'reservations#download_contract', as: 'reservation_download_contract'

end

app/models/guest.rb
class Guest < ActiveRecord::Base
  validates :name, :surname, :gender, :date_of_birth ,:country_of_birth,
   :nationality, :checkin_date, :checkout_date, presence: true
  validates :passport_number, presence: true, if: -> { group_leader? }
  belongs_to :reservation
  scope :leader, -> { where(group_leader: true) }
  scope :pending_sync, -> { where(synced_to_police_portal: false) }

  def full_name
    "#{name} #{surname}"
  end

  GUEST_TYPE = {
    'Single Guest': 16,
    'Householder': 17,
    'Group Leader': 18
  }.with_indifferent_access
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user
  has_many :reservations
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :property
  has_one :user, through: :property
  has_many :guests
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :properties
  has_many :reservations, through: :properties, source: :reservations
  has_many :guests, through: :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def create
    @reservation = Reservation.find(params[:reservation_id])
    @guest = @reservation.guests.create(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @reservation, notice: 'Guest was successfully posted' }
        format.js
      end
    end
  end

  private

  def guest_params
    params.require(:guest).permit(:name, :surname, :gender, :date_of_birth,
     :country_of_birth, :nationality, :passport_number, :group_leader,
     :reservation_id, :checkin_date, :checkout_date)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :find_reservation, only: [:submit, :signed, :email_contract, :download_contract]

  def index
    @reservations = current_user.reservations
  end

  def new
    @properties = current_user.properties
    @reservation = Reservation.new
  end

  def create
    @current_user = current_user
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      @reservation.guests.create!(guest_params[:guest])
      redirect_to @reservation
    else
      render 'new'
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
    @default_checkin_date = @reservation.guests.first.checkin_date
    @default_checkout_date = @reservation.guests.first.checkout_date
  end

  def submit
    police_portal_syncer = PolicePortalSyncer.new(@reservation)
    police_portal_syncer.sync_guests
    contract_generator = ContractGenerator.new(@reservation)
    @signing_url = contract_generator.contract_url
  end

  def signed
    @reservation.update!(contract_signed: true)
    guest = @reservation.guests.leader&.first || @reservation.guests.first
    @email_address = guest.email_address
  end

  def email_contract
    contract_generator = ContractGenerator.new(@reservation)
    contract_generator.download_and_email_contract(params[:email_address])
    redirect_to :back
  end

  def download_contract
    contract_generator = ContractGenerator.new(@reservation)
    file_path = contract_generator.download_contract
    send_file file_path,:type=>"application/pdf", :x_sendfile=>true
  end

  private
  def find_reservation
    @reservation = Reservation.find(params[:reservation_id])
  end

  def reservation_params
    params.require(:reservation).permit(:property_id)
  end

  def guest_params
    params.require(:reservation).permit(guest: [:name, :surname, :gender,
     :date_of_birth, :country_of_birth, :nationality, :passport_number,
     :group_leader, :checkin_date, :checkout_date, :email_address])
  end

  def current_user
    @current_user ||= User.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/guests/_guest.html.erb
<p>
  <%= label_tag "name" %>:
  <%= guest.name %>
</p>
<p>
  <%= label_tag "surname" %>:
  <%= guest.surname %>
</p>
<p>
  <%= label_tag "gender" %>:
  <%= guest.gender %>
</p>
<p>
  <%= label_tag "date_of_birth" %>:
  <%= guest.date_of_birth %>
</p>
<p>
  <%= label_tag "country_of_birth" %>:
  <%= guest.country_of_birth %>
</p>
<p>
  <%= label_tag "nationality" %>:
  <%= guest.nationality %>
</p>
<p>
  <%= label_tag "passport_number" %>:
  <%= guest.passport_number %>
</p>
<p>
  <%= label_tag "group_leader" %>:
  <%= guest.group_leader %>
</p>
<hr>

app/views/guests/create.js.erb
$("#guest_name").val('');
$("#guest_surname").val('');
$("#guest_gender").val('');
$("#guest_date_of_birth").val('');
$("#guest_country_of_birth").val('');
$("#guest_nationality").val('');
$("#guest_passport_number").val('');
$(".guest_infos_container").prepend('<%= j render @guest  %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mymaison</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "https://s3.amazonaws.com/cdn.hellosign.com/public/js/hellosign-embedded.LATEST.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notifier/send_contract.html.erb
<p>Please verify your contract attachment.</p>

app/views/reservations/_add_guest_form.html.erb
<%= form_for([@reservation, @reservation.guests.build],remote: true, :html => {:required => true}) do |f| %>
  <p>
    <%= f.hidden_field :reservation_id %>
    <p>
      <%= f.label "Check In Date: " %>
      <%= f.date_field :checkin_date, value: @default_checkin_date, required: true, min: Date.yesterday, max: Date.today %>
    </p>
    <p>
      <%= f.label "Check Out Date: " %>
      <%= f.date_field :checkout_date, value: @default_checkout_date,required: true %>
    </p>
    <p>
      <%= f.label "name: " %>
      <%= f.text_field :name, required: true %>
    </p>
    <p>
      <%= f.label "surname: " %>
      <%= f.text_field :surname, required: true %>
    </p>
    <p>
      <%= f.label "gender: " %>
      <%= f.select :gender,  ["Male", "Female"], required: true %>
    </p>
    <p>
      <%= f.label "date_of_birth: " %>
      <%= f.date_field :date_of_birth, required: true %>
    </p>
    <p>
      <%= f.label "country_of_birth: " %>
      <%= f.select :country_of_birth,  ["Italy"], required: true %>
    </p>
    <p>
      <%= f.label "nationality: " %>
      <%= f.select :nationality,  ["Italy"], required: true %>
    </p>
    <p>
      <%= f.check_box :group_leader, {checked: false, hidden: true} %>
    </p>

    <%= f.submit "Add Guest + "%>
  </p>
<% end %>

app/views/reservations/index.html.erb
<p><%= @current_user.name%>'s Property Reservations List </p>
<table class="table table-dark table-striped">
  <thead class="thead-light">
    <tr>
      <th>Property</th>
      <th>Guest</th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.property.name  %></td>
        <td><%= reservation.guests.leader.last&.full_name || reservation.guests.first&.full_name %></td>
        <td><%= link_to 'Show', reservation_path(reservation) %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h3><%= link_to 'Add New Guest Reservations', new_reservation_path %></h3>

app/views/reservations/new.html.erb
<%= form_for @reservation, url: reservations_path do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@reservation.errors.count, "error") %> prohibited
        this reservation from being saved:
      </h2>
      <ul>
        <% @reservation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <p>
      <%= f.label "Property: " %>
      <%= f.select :property_id, @properties.collect { |p| [ p.name, p.id ] }, include_blank: false %>
    </p>
    <p> Main Guest Info: </p>
      <%= f.fields_for :guest do |guest| %>
        <p>
          <%= guest.label "Check In Date: " %>
          <%= guest.date_field :checkin_date, required: true, min: Date.yesterday, max: Date.today %>
        </p>
        <p>
          <%= guest.label "Check Out Date: " %>
          <%= guest.date_field :checkout_date, required: true %>
        </p>
        <p>
          <%= guest.label "name: " %>
          <%= guest.text_field :name, required: true %>
        </p>
        <p>
          <%= guest.label "surname: " %>
          <%= guest.text_field :surname, required: true %>
        </p>
        <p>
          <%= guest.label "gender: " %>
          <%= guest.select :gender,  ["Male", "Female"], required: true %>
        </p>
        <p>
          <%= guest.label "date_of_birth: " %>
          <%= guest.date_field :date_of_birth, required: true %>
        </p>
        <p>
          <%= guest.label "country_of_birth: " %>
          <%= guest.select :country_of_birth,  ["Italy"], required: true %>
        </p>
        <p>
          <%= guest.label "nationality: " %>
          <%= guest.select :nationality,  ["Italy"], required: true %>
        </p>
        <p>
          <%= guest.label "passport_number: " %>
          <%= guest.text_field :passport_number, required: true %>
        </p>
        <p>
          <%= guest.label "email_address: " %>
          <%= guest.email_field :email_address, required: true %>
        </p>
        <p>
          <b><%= guest.label "group_leader: " %></b>
          <%= guest.check_box :group_leader %>
        </p>
      <% end %>
  <p>
    <%= f.submit %>
  </p>

<% end %>

<h3><%= link_to 'Home', root_path %></h3>

app/views/reservations/show.html.erb
<p>
  <%= label_tag :property %>:
  <%= @reservation.property.name %>
</p>
<hr>

<p>Guests Info: </p>
<div class="guest_infos_container">
  <% @reservation.guests.reverse.each do |guest| %>
    <div>
      <p>
        <%= label_tag :checkin_date %>:
        <%= guest.checkin_date %>
      </p>

      <p>
        <%= label_tag :checkout_date %>:
        <%= guest.checkout_date %>
      </p>
      <p>
        <%= label_tag "name" %>:
        <%= guest.name %>
      </p>
      <p>
        <%= label_tag "surname" %>:
        <%= guest.surname %>
      </p>
      <p>
        <%= label_tag "gender" %>:
        <%= guest.gender %>
      </p>
      <p>
        <%= label_tag "date_of_birth" %>:
        <%= guest.date_of_birth %>
      </p>
      <p>
        <%= label_tag "country_of_birth" %>:
        <%= guest.country_of_birth %>
      </p>
      <p>
        <%= label_tag "nationality" %>:
        <%= guest.nationality %>
      </p>
      <p>
        <%= label_tag "passport_number" %>:
        <%= guest.passport_number %>
      </p>
      <p>
        <%= label_tag "group_leader" %>:
        <%= guest.group_leader %>
      </p>
      <hr>
    </div>
  <% end %>
</div>
<% if @reservation.guests.pluck(:synced_to_police_portal).any? %>
  <h4>Already Synced to Police Portal ! </h4>
<% elsif @reservation.guests.leader.pending_sync.any? %>
  <h5>Add More Guest to Reservation </h5>
  <%= render 'add_guest_form' %>
<% end %>
<hr>
<% if !@reservation.contract_signed? %>
  <h4>Police Portal and Contract Info.</h4>
  <p>
    <%= button_to 'Submit and Sync', reservation_submit_path(@reservation) %>
    Click 'Submit and Sync' to Sync to Police Portal and/or Generate Contract.
  </p>
<% else %>
  <b>
    Already Signed Contract
    <%= button_to 'Download Contract', reservation_download_contract_path(@reservation) %>
  </b>
<% end %>

<h3><%= link_to 'Home', root_path %></h3>

app/views/reservations/signed.html.erb
<p>Thank you for completing the signing</p>
<p>Email contract?</p>

<%= form_tag reservation_email_contract_path(@reservation) do%>
  Email : <%= text_field_tag 'email_address', @email_address, :size=>"30"%>
  <%= submit_tag "submit",:value => "submit"%>
<%end%>

<p>
  <%= button_to 'Download Contract', reservation_download_contract_path(@reservation) %>
</p>

<h3><%= link_to 'Home', root_path %></h3>

app/views/reservations/submit.html.erb
<script type="text/javascript">
  var signing_url = <%= raw @signing_url.to_json %>;
  var redirect_url = "<%= reservation_signed_path(@reservation) %>";
  HelloSign.init("248a18bc8fe2f1d2e3f91a7319e89251");
  HelloSign.open({
    url: signing_url.data.sign_url,
    skipDomainVerification: true,
    allowCancel: true,
    messageListener: function(eventData) {
      if (eventData.event == HelloSign.EVENT_SIGNED) {
        window.location.replace(redirect_url);
      }
    }
  });
  // window.open('<%= @signing_url %>', '_blank');
</script>

<div>
  <p>Please Sign the document </p>
</div>

<h3><%= link_to 'Home', root_path %></h3>